name: Historical ROI - Chainboost
on:
  schedule:
    - cron: '10 13 * * *'
jobs:
  seedify:
    runs-on: ubuntu-latest
    steps:
      - name: Historical ROI Cronjob
        run: |
          curl -u '${{ secrets.LOGIN }}:${{ secrets.PASSWORD }}' --request POST \
          --url 'https://launchpad-roi-api-rewrite.vercel.app/historical-roi?launchpad=chainboost' \