name: Historical ROI Cronjob
on:
  push:
  schedule:
    - cron: '0 13 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Historical ROI Cronjob
        run: |
          curl -u ${{ secrets.LOGIN }}:${{ secrets.PASSWORD }} --request POST \
          --url 'https://launchpad-roi-api-rewrite.vercel.app/historical-roi' \